"""initial schema

Revision ID: 68db30135371
Revises: 138384c2d74e
Create Date: 2026-03-25 19:01:06.820832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68db30135371'
down_revision: Union[str, Sequence[str], None] = '138384c2d74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_cycle_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_cycle_snapshots_cycle_id'), 'bot_cycle_snapshots', ['cycle_id'], unique=True)
    op.create_table('market_data_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('snapshot_type', sa.String(length=16), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_type', 'source_timestamp', name='uq_market_snapshot_symbol_type_source_ts')
    )
    op.create_index(op.f('ix_market_data_snapshots_snapshot_type'), 'market_data_snapshots', ['snapshot_type'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_source_timestamp'), 'market_data_snapshots', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_symbol'), 'market_data_snapshots', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_owner_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_owner_id'), 'orders', ['broker_owner_id'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('portfolio_account_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('daily_realized_pnl', sa.Float(), nullable=False),
    sa.Column('daily_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('occured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_history_id'), 'trade_history', ['id'], unique=False)
    op.create_index(op.f('ix_trade_history_occured_at'), 'trade_history', ['occured_at'], unique=False)
    op.create_index(op.f('ix_trade_history_symbol'), 'trade_history', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_symbol'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_occured_at'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_id'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('portfolio_account_state')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_owner_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_data_snapshots_symbol'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_source_timestamp'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_snapshot_type'), table_name='market_data_snapshots')
    op.drop_table('market_data_snapshots')
    op.drop_index(op.f('ix_bot_cycle_snapshots_cycle_id'), table_name='bot_cycle_snapshots')
    op.drop_table('bot_cycle_snapshots')
    # ### end Alembic commands ###
